name: terraform-workflow
on:
  push:
    branches:
      - main
      
  pull_request:

  workflow_dispatch: null

jobs:
  job1:
    name: Static Code Analyss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "This is my first yaml file"
